### ISSUE TITLE
ObjectPrinter.extractFields seg-faulting on Windows

### ISSUE THREAD

**Issue by zbaylin** [reasonml/reason-native#264]
After thinking something was wrong with my tests, I was able to get `gdb` working on Windows to see that Rely is crashing at `ObjectPrinter.extractFields`:
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x000000000043eded in camlRelyInternal__ObjectPrinter__extractFields_280 ()
(gdb) bt
#0  0x000000000043eded in camlRelyInternal__ObjectPrinter__extractFields_280 ()
#1  0x000000000965c020 in ?? ()
```

I wish I could get more info but it doesn't seem like much debug info persisted to the executable. If I had to guess, the segfault happens here:
https://github.com/reasonml/reason-native/blob/aec0ac681be7211b4d092262281689c46deb63e1/shared-src/objectPrinter/ObjectPrinter.re#L75
just because I'm not sure what else would cause a SIGSEGV

**Comment by bandersongit** [comment]
Are you able to find provide more specific input that is causing this error? You can use testSkip/testOnly/describeSkip/describeOnly in order to narrow things down.
